### ISSUE TITLE
20i backup cleanup schedule from backblaze

### ISSUE THREAD

**Issue by VirtualworldGlo** [ryanall/20i-reseller-backblaze-b2-backups#10]
Hi Ryan,

Thank you for your help and support, the script is now running.

1> We are not able to delete the old backups, we don't want to keep for '1 month' but only for last '7 days' what should be our input in the script for this ?

2> Also we are not able to exclude our the backup domain (which is used to backup the script), please guide us on how to do that...

3> Can you please let me know what you had bent by Random Domain ( Domain that has not been registered / exist )

Awaiting reply...

__
Best Wishes & Regards,
Lily M.

**Comment by ry-allan** [comment]
Hi there,

1.  Schedule the clean up job to be every 7 days and update the following in manager.php

`const DELETE_BACKUPS_OLDER_THAN = '1 month';`

2. In the same file as above, there is an excludedSites array, add your domain here that you don’t want to backup.

3. Random Domain = A hosting account you have setup that’s just dedicated to your backup activities as per this process.
