### ISSUE TITLE
20i backup - Exclude Site

### ISSUE THREAD

**Issue by VirtualworldGlo** [ryanall/20i-reseller-backblaze-b2-backups#11]
Hi Ryan,

Thank you for your help.

As per your guidance we implemented the below - 

1> When we input the account name in - private $excludedSites = [cloudnetwork.tk]

The backup is not downloading to backblaze, when we tested the Scheduled Task command it shows below message -  
------------------
PHP Notice:  Use of undefined constant cloudnetwork - assumed 'cloudnetwork' in /home/sites/9b/b/b9500fc55c/public_html/manager.php on line 317
PHP Notice:  Use of undefined constant tk - assumed 'tk' in /home/sites/9b/b/b9500fc55c/public_html/manager.php on line 317
------------------
When I remove the domain name from the excluded sites it works. How to exclude the site, What needs to be done to correct this ?

2> Will the script work if we do not use a live domain ?

Awaiting reply...

__
Best Wishes & Regards,
Lily M.

**Comment by ry-allan** [comment]
Hi there,

It needs to be defined as a string like:
`$excludedSites = ['cloudnetwork.tk'];`

Regards
Ryan
