### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by thekingster** [ryanall/20i-reseller-backblaze-b2-backups#12]
I can't see

$excludedBackups in manager.php

Also does this backup to the ftp it is installled on first?

??

**Comment by ry-allan** [comment]
Hi there,

Excluded sites is defined here:
https://github.com/ryanall/20i-reseller-backblaze-b2-backups/blob/master/manager.php#L32

This script only works with backblaze currently although easily adaptable for FTP if you require this feature.

**Comment by thekingster** [comment]
OK thanks. I run it and I just get a blank screen, is that as expected?

Any way I can contact you please? Happy to pay for time.

**Comment by ry-allan** [comment]
Hi there,

The script itself should be invoked via the CLI as per the instructions in the README.md - you’ll see output showing each backup as it’s scheduled/downloaded/etc.

Unfortunately I have very little time to improve this but feel free to open a new issue with anything and I’ll try and assist where I can.

**Comment by thekingster** [comment]
Not so much development, just a few simple questions.

For example why do we excluse the site that it is running from to stop backing up the backups? Does it backup to this FTP first before sending to backblaze?

**Comment by ry-allan** [comment]
Hi there,

As per your initial question, these reason the backup account is excluded - this script will retrieve all sites under your reseller account which would include the account used solely for running this.

If you run the download job, there is a potential window where 20i would backup the account along with any inflight processing of backups which could cause a very big backup containing itself and other backups.

As part of the script processing, it downloads the backup file locally, uploads it to backblaze and then deletes the local copy. FTP isn’t used as part of this.

**Comment by thekingster** [comment]
Thanks

And excluded sites, do you just put for example     

private $excludedSites = [sitea.co.uk,siteb.co.uk];

?

**Comment by ry-allan** [comment]
Hi there,

That’s correct but make sure you define each array item as a string.
