### ISSUE TITLE
need advise

### ISSUE THREAD

**Issue by gegeor** [ryanall/20i-reseller-backblaze-b2-backups#14]
Hello
I tried to use  the script after sometime  but i get these errors:
----------------------------------------------------
20i CLI Backup Manager
---------------------------------------------------------------------------------------
Found 10 sites under this account, checking if we have backups...
---------------------------------------------------------------------------------------
[DOWNLOAD] ☁️️  Found a remote backup for *.gr created at 03-03-2020-17-32-06, downloading
[DOWNLOAD] ☁️️  Found a remote backup for *gr created at 03-03-2020-17-32-06, downloading
downloading
[TRANSFER] ⚡  Upload initiated for backup *****.gr_03-03-2020-17-32-06.zip
PHP Fatal error:  Uncaught ChrisWhite\B2\Exceptions\B2Exception: Received error from B2: incident id c8b86ffcd40a-ntCbNiTZS5axmY0ia6Yz0Q== in /home/sites/10a/c/******/public_html/vendor/cwhite92/b2-sdk-php/src/ErrorHandler.php:36
Stack trace:
#0 /home/sites/10a/c/******/public_html/vendor/cwhite92/b2-sdk-php/src/Http/Client.php(29): ChrisWhite\B2\ErrorHandler::handleErrorResponse(Object(GuzzleHttp\Psr7\Response))
#1 /home/sites/10a/c/******/public_html/vendor/cwhite92/b2-sdk-php/src/Client.php(217): ChrisWhite\B2\Http\Client->request('POST', 'https://pod-000...', Array)
#2 /home/sites/10a/c/********/public_html/manager.php(211): ChrisWhite\B2\Client->upload(Array)
#3 /home/sites/10a/c/********/public_html/manager.php(301): TwentyIBackupManager->transferBackups()
#4 /home/sites/10a/c/*******/public_html/manager.php(318): TwentyIBackupManager->boot()
#5 {main}
  thrown in /home/sites/10a/c/**********/public_html/vendor/cwhite92/b2-sdk-php/src/ErrorHandler.php on line 36

----------------------------------
Any ideas ?
Thank you very much:)

**Comment by ry-allan** [comment]
Hi there,

I’d recommend contacting backblaze with the reference and see if they can provide any insight their end:

Received error from B2: incident id c8b86ffcd40a-ntCbNiTZS5axmY0ia6Yz0Q== 

Is the site large in size?

Regards
Ryan

**Comment by gegeor** [comment]
Thank you:)  The  backup size  is  about 2.5GB 
I will contact  BB  -hope they will look on that...

many thanks:) 
best regards!

**Comment by ry-allan** [comment]
Just to add, that backup size should be fine so definitely have a chat with Backblaze.

Is this an issue that occurs consistently?

**Comment by gegeor** [comment]
Hi
I set it up today after 7-8 months (it was fine then)
Now i see that  2 backups  are  allready  uploaded -the one is the big file  but rest  backups  not  uploaded. seems  that something  is  stoping the procedure? dont know

i have sent ticket to BB  and wait  their response ..as soon i have  answer i will post:)
Many thanks my friend:)

**Comment by gegeor** [comment]
Hi again ,
Just gor answer from BB support : 
-----------
The sdk you are using is unsupported. And this codebase is not handling retries properly. If you’d like to write to our API directly, we have example code of how to properly support retries during upload in our docs here: 

https://www.backblaze.com/b2/docs/uploading.html
--------------------

**Comment by ry-allan** [comment]
Hi there,

Unfortunately this backup script relies on https://github.com/cwhite92/b2-sdk-php which hasn’t been updated in several years.

It’s worth taking a look to see if there is a package that can achieve what’s recommended from backblaze and if you wish, open a PR with the relevant changes and I’d be happy to merge them for others to enjoy too.

Thanks for the detail ☺️

Regards
Ryan

**Comment by gegeor** [comment]
I thank you my friend:)
best regards

**Comment by azeezeladl** [comment]
i have same problem @sudo-ryan 

can u help me ?

**Comment by azeezeladl** [comment]
@gegeor  Did you solve the problem?

**Comment by gegeor** [comment]
> @gegeor Did you solve the problem?

Nope ,never solved that problem-sorry
Not using  20i ,very slow hosting  for me

**Comment by azeezeladl** [comment]
> > @gegeor Did you solve the problem?
> 
> Nope ,never solved that problem-sorry
> Not using 20i ,very slow hosting for me

Slow with me too, for any company hosting you now

**Comment by gegeor** [comment]
cloudways  and hostmantis for  low budget clients
