### ISSUE TITLE
Error on Upload

### ISSUE THREAD

**Issue by thekingster** [ryanall/20i-reseller-backblaze-b2-backups#16]
Got mine working now, but I get this error?

PHP Notice:  404 on https://api.20i.com/package/702105/web/websiteBackup in /home/sites/10a/0/008953edb5/public_html/20i-backup/20i_client.php on line 30
PHP Fatal error:  Uncaught ChrisWhite\B2\Exceptions\B2Exception: Received error from B2: c000_v0001067_t0049 is too busy in /home/sites/10a/0/008953edb5/public_html/20i-backup/vendor/cwhite92/b2-sdk-php/src/ErrorHandler.php:36
Stack trace:
#0 /home/sites/10a/0/008953edb5/public_html/20i-backup/vendor/cwhite92/b2-sdk-php/src/Http/Client.php(29): ChrisWhite\B2\ErrorHandler::handleErrorResponse(Object(GuzzleHttp\Psr7\Response))
#1 /home/sites/10a/0/008953edb5/public_html/20i-backup/vendor/cwhite92/b2-sdk-php/src/Client.php(217): ChrisWhite\B2\Http\Client->request('POST', 'https://pod-000...', Array)
#2 /home/sites/10a/0/008953edb5/public_html/20i-backup/manager.php(218): ChrisWhite\B2\Client->upload(Array)
#3 /home/sites/10a/0/008953edb5/public_html/20i-backup/manager.php(308): TwentyIBackupManager->transferBackups()
#4 /home/sites/10a/0/008953edb5/public_html/20i-backup/manager.php(325): TwentyIBackupManager->boot()
#5 {main}

**Comment by hayatniazi** [comment]
hey, can you please assist - I am getting almost same error.
