### ISSUE TITLE
Can I use that script to back up any website?

### ISSUE THREAD

**Issue by zetagalactic** [ryanall/20i-reseller-backblaze-b2-backups#4]
Hello, thanks for this great script, I'm wondering if you can customize this script to backup a website on the standard hosting accounts. I have Linux hosting account and I want to use this script to make backups for my website, so instead of using API of the i2 can you use FTP or something similar.

Best reagrds,
Mohamed Ali

**Comment by ry-allan** [comment]
Hi Mohamed,

This script was specifically written for use with 20i. There are multiple scripts available on GitHub to allow you to achieve your use case.

Thanks
