### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gegeor** [ryanall/20i-reseller-backblaze-b2-backups#5]
Hello

I am getting  an error / message  when i test  the  cron 
the message is : PHP Notice:  Use of undefined constant gbackup - assumed 'gbackup' in /home/sites/3x/x/xxxxxxxxx30/public_html/manager.php on line 317
PHP Notice:  Use of undefined constant net - assumed 'net' in /home/sites/xa/x/xxxxxxx30/public_html/manager.php on line 317

any ideas ?
Thank you very much
Georgios

**Comment by ry-allan** [comment]
Hi Georgios,

Have you made any changes to the script? The script doesn't have any references to `gbackup` for example.

Regards

**Comment by gegeor** [comment]
Hello
Thank you for your  reply
No changes have been made  but  i think  this  is  because gbackup.net is  my "dummy"  20i account for the  backup
this is  the  line  -perhaps i set  something  wrong there?

 /**
     * @var array
     */
    private $excludedSites = [gbackup.net];

**Comment by ry-allan** [comment]
Yes, you need to wrap your domain as a string:

```
private $excludedSites = ['gbackup.net'];
```

**Comment by gegeor** [comment]
wow
My mistake  ,  that  was  the  problem!!!!! fixed that  now  and  no errors!!
thank you  very much:)
Your script  is awsome, great job  and  so  usefull!!!

Regards
Georgios
