### ISSUE TITLE
Update this script according to new api of 20i

### ISSUE THREAD

**Issue by falconhoster** [ryanall/20i-reseller-backblaze-b2-backups#6]
Update this script according to new api of 20i

**Comment by ry-allan** [comment]
Hi there,

This script supports the existing API for backing up websites and downloading them. Which actions are you referring to that don’t currently work or you’d like support for?

Thanks

**Comment by falconhoster** [comment]
Can host this script on my storage VPS then download all backup in my vps instead of transferring to backblaze.

**Comment by ry-allan** [comment]
Hi there,

All you will need to do is comment out this line https://github.com/ryanall/20i-reseller-backblaze-b2-backups/blob/91fd5a8ced7d750a3bf4a3c609bca7058cdf5f75/manager.php#L301 and modify the cleanup method to delete backups older than a specific time frame locally if your not wanting B2.

Thanks

**Comment by falconhoster** [comment]
And how i can make Different folder for daily backups like this script save all backups to /backup but i want some thing like /baclup/12-24-2017

**Comment by ry-allan** [comment]
Hi,

It already does this - see line https://github.com/ryanall/20i-reseller-backblaze-b2-backups/blob/master/manager.php#L157

Thanks

**Comment by falconhoster** [comment]
How i can solve this error http://prntscr.com/hrqjby  Connection time out when downloading backup

**Comment by ry-allan** [comment]
Hi there,

Can you download the backup direct through the API outside of the script?

I’d recommend opening a support ticket with 20i if your issue continues, this is unrelated to this script.

Thanks

**Comment by falconhoster** [comment]
This script is hosted on my VPS not on 20i. 

Can you please take a look     Team viewer ID 506 079 485   Pass 8428

**Comment by ry-allan** [comment]
Hi there,

The script should work regardless of where it is hosted. I’d recommend trying the download link direct returned from the API to see if you can download the file direct.

Thanks

**Comment by falconhoster** [comment]
It's working http://prntscr.com/hrqmex but why i am getting this error from my vps ?

**Comment by ry-allan** [comment]
Hi there,

I’d recommend setting a larger timeout time using http://php.net/stream_set_timeout. The script was tested using 20i’s hosting accounts (as per setup instructions).

Thanks

**Comment by falconhoster** [comment]
Thanks for your reply,

Any video tutorial?

**Comment by ry-allan** [comment]
Hi there,

Unfortunately not, the link I provided should provide enough context.

Thanks

**Comment by falconhoster** [comment]
Thank you for reply,

I don't have knowledge in PHP :)

I will pay you if you can do it for me Via Team viewer.

**Comment by ry-allan** [comment]
Hi there,

Sorry I don’t have any capacity to provide invidual development help. I’d recommend using Backblaze and a 20i hosting account, backblaze is extremely cheap and would likely remove your issues if your running it in 20i’s servers as the script was only tested there.

Thanks

**Comment by falconhoster** [comment]
Thanks for your reply,

Unfortunately, This script was running fine but 20i suspended my account for using it so i bought an vps with big hard drive and i want to use it here.

**Comment by ry-allan** [comment]
Hi there,

Was there a specific reason they provided for suspending your account? It should be fine as long as your using backblaze and not your 20i account for storing all the backups.

Thanks

**Comment by falconhoster** [comment]
Thanks for your reply,

Support Ticket  Screen shots
1  http://prntscr.com/hrr0ef
2  http://prntscr.com/hrr0r2

**Comment by ry-allan** [comment]
Hi there,

If you setup all the actions specified in the reader, the script will automatically clean up after itself to prevent storing over 650GB of files. With the full setup complete, once the file has been downloaded and uploaded, it is removed from the local file system.

Thanks

**Comment by falconhoster** [comment]
Yes it was being removed after downloading but they said reason of suspension is High usage in Bandwidth.

**Comment by ry-allan** [comment]
You must have a huge amount of sites and disk space usage? I have the backup script to run once per week.

Thanks

**Comment by falconhoster** [comment]
I  have more than 284 Packages. that's why i bought my own vps and i want to store backup in my vps without Using diskspace of 20i.

Please Add me here https://facebook.com/usamaseo1

**Comment by ry-allan** [comment]
Hi there,

I’d recommend if you need any additional work done to make the script compatible with your VPS to checkout a small jobs site such as Fiverr. 👍🏻

Thanks

**Comment by falconhoster** [comment]
I am Expert in Marketing i can help you to sell out your scripts : )

**Comment by ry-allan** [comment]
Thank you for the offer however this script is free for everyone.

I use 20i myself and wanted a cheaper solution to backup my few sites so created this.

Hopefully others can use it and save them some money like it has for me. 😊

**Comment by falconhoster** [comment]
I am not on this script which is already free.

But i know you can make some time saving scripts for Other purposes :) 

And i got 100+ Clients within 2 months  without spending money on Advertising For my Web Hosting Business.

I tried Commission junction this month and got 2 sales on 35 Clicks only :) http://prntscr.com/hrr6vk

I have Master skills in SEO :1st_place_medal:  Can sell any script.

**Comment by falconhoster** [comment]
Selling own Product is Good business but it's not easy to sell them out. :)

**Comment by ry-allan** [comment]
Thanks, I’ll bare this mind for the future. 👍🏻

**Comment by falconhoster** [comment]
Add me on FB. i have some ideas to discus on Developing some time saving Scripts for SEO and Sell them out.
