### ISSUE TITLE
[QUESTION](13-8-19) -Backup Script Help Requested

### ISSUE THREAD

**Issue by VirtualworldGlo** [ryanall/20i-reseller-backblaze-b2-backups#9]
Hi,

Thank you for taking time to create a script to help the community :)

I have two questions 

1> Do we have any example script to see what to fill where in the script for a new user 
(as offered in - https://whmbackup.solutions (cPanel / WHM Backup Solution)

2> Do we have any other option for remote backup than  such as Remote FTP Storage other than backblaze. we plan to host the backup domain with 201 and not on ant other server. But instead of Backup Blaze if we can use remote FTP as we have 10 TB space 

__
Best Wishes & Regards,
Naveen A.

**Comment by ry-allan** [comment]
Hi @VirtualworldGlo,

The script uses the 20i API to automatically retrieve all users under your reseller account so there isn't a need to manually add packages. You can however exclude sites in the script, simply add the package domain to the `$excludedSites` array.

Regading your second point, yes, it is possible, take a look at the available ftp methods available for PHP. Ideally you could create an adapter for each storage provider which would allow you the flexibility of choosing which one you would like to use.

Unfortunately since my use case is solely for 20i currently, feel free to submit a PR adding this functionality and once reviewed, I will happily merge it.

Thanks
Ryan

**Comment by VirtualworldGlo** [comment]
Hi Ryan,

Thank you for your reply.

We will use this script only for 20i so we are concerned about that and we would like to backup twice a week only and keep for 2 months to a remote  BACKBLAZE B2.

We tried setting up the script and faced the below issues

1> we are not sure what to fill where properly , can you please help us with an example.

2>  I am trying to run scheduled task but getting error-
 PHP Fatal error: Uncaught Error: Undefined class constant '.....3f72b42' in /home/sites/9b/b/....0fc55c/public_html/manager.php:62

Where do I find ACCOUNT_ID, and APP_KEY  in Backblaze ?

3> Does this backup contain email backup ?

Thank you for your help & support.
__
Best Wishes & Regards,
Naveen A.

**Comment by VirtualworldGlo** [comment]
Hi,

Trying to setup Backblaze - as in the below script

https://github.com/ryanall/20i-reseller-backblaze-b2-backups/blob/master/manager.php

Here user is using :
--------------------------
use ChrisWhite\B2\Client as BackBlazeClient;
use ChrisWhite\B2\Bucket;
--------------------------

What should I put in the dotted place "................" in the above below in place of - "ChrisWhite" as shown in the above code - 
--------------------------
use ................\B2\Client as BackBlazeClient;
use ................\B2\Bucket;
--------------------------

Best Wishes & Regards,
Lily M.

**Comment by ry-allan** [comment]
Hi @VirtualworldGlo,

**You need to get your application key and account ID from your backblaze interface**:
https://www.backblaze.com/blog/b2-application-keys/

**You then need to add these values here**:
https://github.com/ryanall/20i-reseller-backblaze-b2-backups/blob/master/manager.php#L40

**Currently 20i doesn't backup email with a backup, only website and/or database files. You can configure this here**:
https://github.com/ryanall/20i-reseller-backblaze-b2-backups/blob/master/manager.php#L50

**You can also configure how long a backup should be kept for here**:
https://github.com/ryanall/20i-reseller-backblaze-b2-backups/blob/master/manager.php#L45

Regards
Ryan

**Comment by VirtualworldGlo** [comment]
Hi Ryan,

Thank you for your help and support, the script is now running.

1> We are not able to delete the old backups, we don't want to keep for '1 month' but only for last '7 days' what should be our input in the script for this ?

2> Also we are not able to exclude our the backup domain (which is used to backup the script), please guide us on how to do that...

3> Can you please let me know what you had bent by Random Domain ( Domain that has not been registered / exist )

Awaiting reply...


__
Best Wishes & Regards,
Lily M.
